/* eslint-disable react/no-unescaped-entities */
// Style
import styles from './index.module.css';

// Next
import Head from 'next/head';

// Librairies
import { useForm, SubmitHandler } from 'react-hook-form';

// Type
type FormData = {
    username: string;
    password: string;
};

export default function index() {
    const {
        register,
        handleSubmit,
        formState: { errors },
    } = useForm<FormData>();

    const onSubmit: SubmitHandler<FormData> = (data) => console.log(data);

    return (
        <>
            <Head>
                <title>Mickaël BOSSA - Web developer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container">
                <div className={styles.subcontainer}>
                    <div className={styles.loginPanel}>
                        <h1 className={styles.title}>
                            Interface administrateur
                        </h1>
                        <form
                            onSubmit={handleSubmit(onSubmit)}
                            className={styles.form}
                        >
                            <div className={styles.labelAndInput}>
                                <label htmlFor="username">
                                    Nom d'utilisateur :
                                </label>
                                <input
                                    className={styles.loginInputs}
                                    type="text"
                                    placeholder="JohnDoe"
                                    {...(register('username'),
                                    {
                                        required: true,
                                    })}
                                />
                                {errors.username && (
                                    <span>Ce champ est requis</span>
                                )}
                            </div>
                            <div className={styles.labelAndInput}>
                                <label htmlFor="password">Mot de passe :</label>
                                <input
                                    className={styles.loginInputs}
                                    type="password"
                                    placeholder="Mot de passe"
                                    {...(register('password'),
                                    {
                                        required: true,
                                    })}
                                />
                                {errors.password && (
                                    <span>Ce champ est requis</span>
                                )}
                            </div>
                            <button className={styles.submitBtn} type="submit">
                                Se connecter
                            </button>
                        </form>
                    </div>
                </div>
            </main>
        </>
    );
}
